CREATE TABLE Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                       name varchar(50) UNIQUE,
                       year int
);

CREATE TABLE Book(
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                     name varchar(50),
                     author varchar(50),
                     year int,
                     person_id int DEFAULT null REFERENCES Person(id) ON DELETE RESTRICT
);

INSERT INTO Book(name, author, year) VALUES ('Над пропастью во ржи', 'Джером Сэлинджер', 1951),
                                            ('День опричника', 'Владимир Сорокин', 2006),
                                            ('Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018),
                                            ('Философия Java', 'Брюс Эккель', 2018),
                                            ('Психопатология обыденной жизни', 'Фрейд Зигмунд', 1904),
                                            ('Игра в бисер', 'Герман Гессе', 1943),
                                            ('Бытие и время', 'Мартин Хайдеггер', 1927);

INSERT INTO Person(name, year) VALUES ('John Smith', 1985),
                                      ('Jane Doe', 1990),
                                      ('Michael Johnson', 1978),
                                      ('Emily White', 2000),
                                      ('Robert Brown', 1982),
                                      ('Sophia Lee', 1995),
                                      ('David Davis', 1970),
                                      ('Olivia Adams', 1988),
                                      ('William Turner', 1998),
                                      ('Ava Harris', 1975);

INSERT INTO Book(name, author, year) VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 1925),
                                            ('To Kill a Mockingbird', 'Harper Lee', 1960),
                                            ('1984', 'George Orwell', 1949),
                                            ('Pride and Prejudice', 'Jane Austen', 1813),
                                            ('The Catcher in the Rye', 'J.D. Salinger', 1951),
                                            ('The Lord of the Rings', 'J.R.R. Tolkien', 1954),
                                            ('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 1997),
                                            ('Moby-Dick', 'Herman Melville', 1851),
                                            ('The Hobbit', 'J.R.R. Tolkien', 1937),
                                            ('War and Peace', 'Leo Tolstoy', 1869);

DROP TABLE Person;
DROP TABLE Book;

SELECT * FROM Person;
SELECT * FROM Book;